// HERE YOU EXPORT ALL ACTIONS FOR ENTIRE APP
export const TEST_ACTION_START = 'TEST_ACTION_START'
export const TEST_ACTION_SUCCESS = 'TEST_ACTION_SUCCESS'
export const TEST_ACTION_FAIL = 'TEST_ACTION_FAIL'
